# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "opensuse/Leap-15.4.x86_64"
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 2
    libvirt.memory = 4096
    libvirt.disk_bus = "virtio"
    libvirt.disk_driver :cache => "writeback"
  end
  config.vm.hostname = "opensuse-leap-dev"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  #config.vm.network "private_network", ip: "192.168.50.10", gateway: "192.168.50.1"
  config.vm.network "public_network", dev: "br0", mode: "bridge", type: "bridge"
  config.vm.provision "file", source: "./id_ed25519", destination: "/tmp/id_ed25519"
  config.vm.provision "file", source: "./id_ed25519.pub", destination: "/tmp/id_ed25519.pub"

  config.vm.provision "shell", path: "bootstrap.sh"
end
