# -*- mode: ruby -*-
# vi: set ft=ruby :

$PUBLIC_NET_DEVICE="br0"
$BRANCH = "development-setup"

Vagrant.configure("2") do |config|
  config.vm.box = "opensuse/Leap-15.4.x86_64"
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 2
    libvirt.memory = 4096
    libvirt.disk_bus = "virtio"
    libvirt.disk_driver :cache => "writeback"
  end
  config.vm.hostname = "opensuse-leap-dev"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "public_network", dev: $PUBLIC_NET_DEVICE, mode: "bridge", type: "bridge"
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provision "shell", path: "bootstrap.sh", env: {"BRANCH" => $BRANCH}
end